/* Automatically generated by '../script/build-entry.js' */

import icsmButton from './button/index.js';
import icsmCell from './cell/index.js';
import icsmCellGroup from './cellGroup/index.js';
import icsmCalendar from './calendar/index.js';
import icsmCascader from './cascader/index.js';
import icsmDatePicker from './datePicker/index.js';
import icsmGridItem from './gridItem/index.js';
import icsmField from './field/index.js';
import icsmGrid from './grid/index.js';
import icsmIcon from './icon/index.js';
import icsmCheckbox from './checkbox/index.js';
import icsmNumberKeyboard from './numberKeyboard/index.js';
import icsmPickerGroup from './pickerGroup/index.js';
import icsmPicker from './picker/index.js';
import icsmPopup from './popup/index.js';
import icsmSpace from './space/index.js';
import icsmRadio from './radio/index.js';
import icsmRadioGroup from './radioGroup/index.js';
import icsmSwipeItem from './swipeItem/index.js';
import icsmTimePicker from './timePicker/index.js';
import icsmSwipe from './swipe/index.js';

// 主题设置 & 版本号
import setTheme from '@/utils/themes.js'
import pkg from '../package.json'
import '../locale/index'


const components = [
  icsmButton,
  icsmCell,
  icsmCellGroup,
  icsmCalendar,
  icsmCascader,
  icsmDatePicker,
  icsmGridItem,
  icsmField,
  icsmGrid,
  icsmIcon,
  icsmCheckbox,
  icsmNumberKeyboard,
  icsmPickerGroup,
  icsmPicker,
  icsmPopup,
  icsmSpace,
  icsmRadio,
  icsmRadioGroup,
  icsmSwipeItem,
  icsmTimePicker,
  icsmSwipe
];

const install = (app) => {
  components.forEach((i) => {
    app.use(i)
  })
  
  setTimeout(()=>{
    setTheme()
  })
}

const icsmUi = {
  version: pkg.version,
  install
}

export {
  install,
  icsmButton,
  icsmCell,
  icsmCellGroup,
  icsmCalendar,
  icsmCascader,
  icsmDatePicker,
  icsmGridItem,
  icsmField,
  icsmGrid,
  icsmIcon,
  icsmCheckbox,
  icsmNumberKeyboard,
  icsmPickerGroup,
  icsmPicker,
  icsmPopup,
  icsmSpace,
  icsmRadio,
  icsmRadioGroup,
  icsmSwipeItem,
  icsmTimePicker,
  icsmSwipe
}

export default icsmUi
