/* Automatically generated by '../script/build-entry.js' */

import icsmButton from './button/index.js';
import icsmCell from './cell/index.js';
import icsmCascader from './cascader/index.js';
import icsmCalendar from './calendar/index.js';
import icsmCheckbox from './checkbox/index.js';
import icsmCellGroup from './cellGroup/index.js';
import icsmCol from './col/index.js';
import icsmDatePicker from './datePicker/index.js';
import icsmField from './field/index.js';
import icsmImage from './image/index.js';
import icsmGrid from './grid/index.js';
import icsmGridItem from './gridItem/index.js';
import icsmIcon from './icon/index.js';
import icsmLazyload from './lazyload/index.js';
import icsmList from './list/index.js';
import icsmNumberKeyboard from './numberKeyboard/index.js';
import icsmLoading from './loading/index.js';
import icsmNotify from './notify/index.js';
import icsmPicker from './picker/index.js';
import icsmPopup from './popup/index.js';
import icsmPickerGroup from './pickerGroup/index.js';
import icsmRadio from './radio/index.js';
import icsmProgress from './progress/index.js';
import icsmSpace from './space/index.js';
import icsmRow from './row/index.js';
import icsmSwipeItem from './swipeItem/index.js';
import icsmRadioGroup from './radioGroup/index.js';
import icsmSwipe from './swipe/index.js';
import icsmTab from './tab/index.js';
import icsmTag from './tag/index.js';
import icsmToast from './toast/index.js';
import icsmTabs from './tabs/index.js';
import icsmTimePicker from './timePicker/index.js';

// 主题设置 & 版本号
import setTheme from '@/utils/themes.js'
import pkg from '../package.json'
import '../locale/index'


export * from "vant/es/toast/index.mjs";
export * from "vant/es/notify/index.mjs";


const components = [
  icsmButton,
  icsmCell,
  icsmCascader,
  icsmCalendar,
  icsmCheckbox,
  icsmCellGroup,
  icsmCol,
  icsmDatePicker,
  icsmField,
  icsmImage,
  icsmGrid,
  icsmGridItem,
  icsmIcon,
  icsmLazyload,
  icsmList,
  icsmNumberKeyboard,
  icsmLoading,
  icsmNotify,
  icsmPicker,
  icsmPopup,
  icsmPickerGroup,
  icsmRadio,
  icsmProgress,
  icsmSpace,
  icsmRow,
  icsmSwipeItem,
  icsmRadioGroup,
  icsmSwipe,
  icsmTab,
  icsmTag,
  icsmToast,
  icsmTabs,
  icsmTimePicker
];

const install = (app) => {
  components.forEach((i) => {
    app.use(i)
  })
  
  setTimeout(()=>{
    setTheme()
  })
}

const icsmUi = {
  version: pkg.version,
  install
}

export {
  install,
  icsmButton,
  icsmButton as Button,
  icsmCell,
  icsmCell as Cell,
  icsmCascader,
  icsmCascader as Cascader,
  icsmCalendar,
  icsmCalendar as Calendar,
  icsmCheckbox,
  icsmCheckbox as Checkbox,
  icsmCellGroup,
  icsmCellGroup as CellGroup,
  icsmCol,
  icsmCol as Col,
  icsmDatePicker,
  icsmDatePicker as DatePicker,
  icsmField,
  icsmField as Field,
  icsmImage,
  icsmImage as Image,
  icsmGrid,
  icsmGrid as Grid,
  icsmGridItem,
  icsmGridItem as GridItem,
  icsmIcon,
  icsmIcon as Icon,
  icsmLazyload,
  icsmLazyload as Lazyload,
  icsmList,
  icsmList as List,
  icsmNumberKeyboard,
  icsmNumberKeyboard as NumberKeyboard,
  icsmLoading,
  icsmLoading as Loading,
  icsmNotify,
  icsmNotify as Notify,
  icsmPicker,
  icsmPicker as Picker,
  icsmPopup,
  icsmPopup as Popup,
  icsmPickerGroup,
  icsmPickerGroup as PickerGroup,
  icsmRadio,
  icsmRadio as Radio,
  icsmProgress,
  icsmProgress as Progress,
  icsmSpace,
  icsmSpace as Space,
  icsmRow,
  icsmRow as Row,
  icsmSwipeItem,
  icsmSwipeItem as SwipeItem,
  icsmRadioGroup,
  icsmRadioGroup as RadioGroup,
  icsmSwipe,
  icsmSwipe as Swipe,
  icsmTab,
  icsmTab as Tab,
  icsmTag,
  icsmTag as Tag,
  icsmToast,
  icsmToast as Toast,
  icsmTabs,
  icsmTabs as Tabs,
  icsmTimePicker,
  icsmTimePicker as TimePicker
}

export default icsmUi
